### ISSUE TITLE
Setup Github Repo for GitGotGo

### ISSUE THREAD

**Issue by Amckenzie93** [GitGotGo1/sem#1]
We need to create a GitHub project containing a repository for each of us to access and update in branches to meet the requirements of the coursework.

**Comment by Dillon-Brown** [comment]
The Repo is sem under the organisation GitGotGo1: https://github.com/GitGotGo1/sem I've invited everyone to be a collaborator so you have write access. I'd suggest doing the following commands to get a local copy:

1. git init
2. git remote add upstream https://github.com/GitGotGo1/sem.git
3. git fetch --all
4. git pull origin master
5. git checkout upstream/develop -b develop
