### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Amckenzie93** [GitGotGo1/sem#3]
As a team we need to define our Code of Conduct to set out our plan and responsibilities going forwards as a team.

**Comment by Dillon-Brown** [comment]
I'd suggest whoever picks this up to take a look at: https://www.contributor-covenant.org/version/1/4/code-of-conduct.htm. It's fairly standard across open source projects

**Comment by rosshardie** [comment]
Thanks I'll check it out and use it as a template of what to do.
