### ISSUE TITLE
All the capital cities in a continent organised by largest population to smallest.

### ISSUE THREAD

**Issue by rosshardie** [GitGotGo1/sem#30]
As a user I want to be able to see all the capital cities in a continent organised by population from largest to smallest

**Comment by Amckenzie93** [comment]
Population Report
For the population reports, the following information is requested:

* The name of the continent/region/country.
* The total population of the continent/region/country.
* The total population of the continent/region/country living in cities (including a %).
* The total population of the continent/region/country not living in cities (including a %).

**Comment by Amckenzie93** [comment]
Capital City Report
A capital city report requires the following columns:

* Name.
* Country.
* Population.

**Comment by Amckenzie93** [comment]
-- All the capital cities in a Continent organised by largest to smallest.
SELECT 
	t1.Continent AS 'Continent Name',
	t2.name AS 'Capital City',
	t2.population AS 'Capital City Population'
FROM 
	(select country.Name, country.Continent, country.capital FROM country) as t1,
	(select city.name, city.population, city.ID FROM city) as t2
    where 
		t1.capital = t2.id 
        AND 
		t1.Continent = 'Europe' -- Continent PROVIDED BY THE USER 
    order by t2.population DESC;

**Comment by Amckenzie93** [comment]
PR Raised - https://github.com/GitGotGo1/sem/pull/68
