### ISSUE TITLE
The top number of populated capital cities in a continent where the number is provided by the user.

### ISSUE THREAD

**Issue by rosshardie** [GitGotGo1/sem#33]
As a user I want to be able to see the top number of populated capital cities in a continent where the number is specified by me

**Comment by Amckenzie93** [comment]
Population Report
For the population reports, the following information is requested:

* The name of the continent/region/country.
* The total population of the continent/region/country.
* The total population of the continent/region/country living in cities (including a %).
* The total population of the continent/region/country not living in cities (including a %).

**Comment by Amckenzie93** [comment]
Capital City Report
A capital city report requires the following columns:

* Name.
* Country.
* Population.

**Comment by Amckenzie93** [comment]
-- The top number of populated capital cities in a CONTINENT where the number is provided by the user.
SELECT 
	t1.Continent AS 'Continent Name',
	t2.name AS 'Capital City',
	t2.population AS 'Capital City Population'
FROM 
	(select country.Name, country.Continent, country.capital FROM country) as t1,
	(select city.name, city.population, city.ID FROM city) as t2
    where 
		t1.capital = t2.id 
        AND 
		t1.Continent = 'Asia' -- CONTINENT PROVIDED BY THE USER 
    order by t2.population DESC
LIMIT 50; -- NUMBER PROVIDED BY THE USER, IN THIS CASE TOP 10 COUNTRIES
