### ISSUE TITLE
Project setup final steps

### ISSUE THREAD

**Issue by Amckenzie93** [GitGotGo1/sem#4]
As our project is to be worked on by several members of the team we need to setup our project to the following requirements:

- Project builds to self-contained JAR with Maven.
- Dockerfile for project works
- Travis CI for project with working build using JAR, and Docker on Travis CI

**Comment by Dillon-Brown** [comment]
I've setup Travis to trigger on all pushed and PR's: https://travis-ci.com/GitGotGo1/sem/builds/98597939. We'll need to discuss how we are going to be pushing changes to this Repo. The standard would be to fork this repository and then add the the forked Repo as a remote, then you would make a pull request to the develop branch which could then be code-reviewed before being merged in.

**Comment by Amckenzie93** [comment]
Hey Dillon,

this process makes sense to me - very similar to what we use at work so I'm
happy to go with that process moving forward if you guys are?
