### ISSUE TITLE
Capital City Report

### ISSUE THREAD

**Issue by rosshardie** [GitGotGo1/sem#47]
As a user I want to be able to see the name, country and population of any capital city specified by me

**Comment by Amckenzie93** [comment]
Capital City Report
A capital city report requires the following columns:

* Name.
* Country.
* Population.

**Comment by Amckenzie93** [comment]
Population Report
For the population reports, the following information is requested:

* The name of the continent/region/country.
* The total population of the continent/region/country.
* The total population of the continent/region/country living in cities (including a %).
* The total population of the continent/region/country not living in cities (including a %).

**Comment by Amckenzie93** [comment]
Have produced the SQL required for this report - need a front end in the application to hook this into. 

```
SELECT cities.name AS 'Capital City', cities.Population, country.Continent
FROM country 
JOIN city as cities ON cities.ID = country.Capital
WHERE cities.name LIKE 'kabul' -- where clause is where the user would enter their search queiry for their chosen capital city. 
```
