### ISSUE TITLE
Overall project goals captured

### ISSUE THREAD

**Issue by Amckenzie93** [GitGotGo1/sem#5]
This ticket contains all information required of our team to complete our project. each of the items in this ticket will eventually be broken down into workable tickets for each of us with user stories, use cases, and work estimates.

The tickets that will be created based on the information found within this ticket will be done so via ZUBE.io

_______________________________________________________________________________________________________________

> You will work on the project as a Scrum team. Details on Scrum are provided in Lecture 2, including an FAQ on how to apply Scrum in the module.
> 
> You work for an organisation that requires reporting on population information. You have been tasked with designing and implementing a new system to allow easy access to this population information. The organisation has provided you with an SQL database to work from available here.
> 
> The organisation has asked for the following reports to be generated:
> 
> Country Reports:
> * All the countries in the world organised by largest population to smallest.
> * All the countries in a continent organised by largest population to smallest.
> * All the countries in a region organised by largest population to smallest.
> * The top N populated countries in the world where N is provided by the user.
> * The top N populated countries in the world where N is provided by the user.
> * The top N populated countries in a region where N is provided by the user.
>
> City Reports:
> * All the cities in the world organised by largest population to smallest.
> * All the cities in a continent organised by largest population to smallest.
> * All the cities in a region organised by largest population to smallest.
> * All the cities in a country organised by largest population to smallest.
> * All the cities in a district organised by largest population to smallest.
> * The top N populated cities in the world where N is provided by the user.
> * The top N populated cities in a continent where N is provided by the user.
> * The top N populated cities in a region where N is provided by the user.
> * The top N populated cities in a country where N is provided by the user.
> * The top N populated cities in a district where N is provided by the user.
>
> Capital City Reports:
> * All the capital cities in the world organised by largest population to smallest.
> * All the capital cities in a continent organised by largest population to smallest.
> * All the capital cities in a region organised by largest to smallest.
> * The top N populated capital cities in the world where N is provided by the user.
> * The top N populated capital cities in a continent where N is provided by the user.
> * The top N populated capital cities in a region where N is provided by the user.
>
> Population Reports:
> * The population of people, people living in cities, and people not living in cities in each continent.
> * The population of people, people living in cities, and people not living in cities in each region.
> * The population of people, people living in cities, and people not living in cities in each country.
>
> Additionally, the following information should be accessible to the organisation:
> * The population of the world.
> * The population of a continent.
> * The population of a region.
> * The population of a country.
> * The population of a district.
> * The population of a city.
>
> Finally, the organisation has asked if it is possible to provide the number of people who speak the following the following languages from greatest number to smallest, including the percentage of the world population:
> * Chinese.
> * English.
> * Hindi.
> * Spanish.
> * Arabic.
>
> Country Report
> A country report requires the following columns:
> * Code.
> * Name.
> * Continent.
> * Region.
> * Population.
> * Capital.
>
> City Report
> A city report requires the following columns:
> * Name.
> * Country.
> * District.
> * Population.
>
> Capital City Report
> A capital city report requires the following columns:
> * Name.
> * Country.
> * Population.
>
> Population Report
> For the population reports, the following information is requested:
> * The name of the continent/region/country.
> * The total population of the continent/region/country.
> * The total population of the continent/region/country living in cities (including a %).
> * The total population of the continent/region/country not living in cities (including a %).

**Comment by Amckenzie93** [comment]
@rosshardie @Causeless @Dillon-Brown i feel due to the number of tasks that need to be created as user stories, with full use cases defined along with a use case diagram ..we all need to split this up and work on it in quarters as this is all thats left to be done for Tuesdays code review. 

Everything else has been covered by both github, the code and continual integration Dillon has set up along with the kanban and sprint boards with issues and epics i've set up with Zube.

Tomorrows going to be a bit of a cram.

**Comment by Dillon-Brown** [comment]
Created a new sprint called "Code-Review 2".
